

import { ColorThemes } from 'src/types/common';

export const foregroundTokens = ["generalPrimary", "generalPrimaryInverted", "generalSecondary", "generalTertiary", "generalLink", "generalLinkVisited", "generalLinkPressed", "generalInteractive", "generalInteractiveInverted", "generalInteractiveInvertedAlt", "generalWhiteStable", "generalBlackWhite", "generalTransparent", "brandBrand1", "brandBrand2", "statusInfo", "statusInfoInverted", "statusInfoSubdued", "statusSuccess", "statusSuccessSubdued", "statusWarning", "statusWarningSubdued", "statusError", "statusErrorSubdued", "statusDisabled"] as const;

export const borderTokens = ["generalMain", "generalMainSubtle", "generalMainSolid", "generalInteractive", "generalInteractiveInverted", "generalInteractiveHovered", "generalInteractivePressed", "generalWhite", "brandBrand1", "brandBrand2", "statusInfo", "statusInfoInverted", "statusInfoSubdued", "statusSuccessSubdued", "statusWarning", "statusWarningSubdued", "statusError", "statusErrorSubdued", "statusDisabled", "statusOffsetGeneral", "statusOffsetError"] as const;

export const backgroundTokens = ["generalMain", "generalMainInverted", "generalMainAltDarkMode", "generalMainAlt", "generalUnderlying", "generalNoticeable", "generalNegative", "generalNegativeSolid", "generalNegativeSubdued", "generalInteractive", "generalInteractiveInverted", "generalInteractiveSubdued", "generalOverlay", "generalOverlaySubtle", "generalOverlayOnAccentHovered", "generalOverlayOnAccentPressed", "generalOverlayOnColorlessHovered", "generalOverlayOnColorlessPressed", "generalOverlayOnColorlessInvertedHovered", "generalOverlayOnColorlessInvertedPressed", "brandBrand1Primary", "brandBrand1SecondaryHovered", "brandBrand1SecondaryPressed", "brandBrand2Primary", "brandBrand2SecondaryHovered", "brandBrand2SecondaryPressed", "statusInfo", "statusInfoHovered", "statusInfoPressed", "statusInfoInvertedHovered", "statusInfoInvertedPressed", "statusSuccess", "statusWarning", "statusWarningHovered", "statusWarningPressed", "statusError", "statusErrorHovered", "statusErrorPressed", "statusDisabled", "statusDisabledSubtle"] as const;
        
export const colorValues: ColorThemes = {
  "lightTheme": {
    "foreground": {
      "generalPrimary": "#262e34",
      "generalPrimaryInverted": "#ffffff",
      "generalSecondary": "#6e6e70",
      "generalTertiary": "#868687",
      "generalLink": "#006adc",
      "generalLinkVisited": "#5eb0ef",
      "generalLinkPressed": "#00254d",
      "generalInteractive": "#505050",
      "generalInteractiveInverted": "#d9e2fc",
      "generalInteractiveInvertedAlt": "#ffffff",
      "generalWhiteStable": "#ffffff",
      "generalBlackWhite": "#000000",
      "generalTransparent": "rgba(0, 0, 0, 0.4392)",
      "brandBrand1": "#5146CE",
      "brandBrand2": "#1A9991",
      "statusInfo": "#006adc",
      "statusInfoInverted": "#7ebfff",
      "statusInfoSubdued": "#0091ff",
      "statusSuccess": "#18794e",
      "statusSuccessSubdued": "#30a46c",
      "statusWarning": "#c17a00",
      "statusWarningSubdued": "#ffb224",
      "statusError": "#cd2b31",
      "statusErrorSubdued": "#e5484d",
      "statusDisabled": "#909091"
    },
    "border": {
      "generalMain": "#909091",
      "generalMainSubtle": "#e3e3e5",
      "generalMainSolid": "#262e34",
      "generalInteractive": "#505050",
      "generalInteractiveInverted": "#d9e2fc",
      "generalInteractiveHovered": "#707070",
      "generalInteractivePressed": "#262e34",
      "generalWhite": "#ffffff",
      "brandBrand1": "#5146CE",
      "brandBrand2": "#1A9991",
      "statusInfo": "#006adc",
      "statusInfoInverted": "#7ebfff",
      "statusInfoSubdued": "#0091ff",
      "statusSuccessSubdued": "#30a46c",
      "statusWarning": "#c17a00",
      "statusWarningSubdued": "#ffb224",
      "statusError": "#cd2b31",
      "statusErrorSubdued": "#e5484d",
      "statusDisabled": "#c7c7c9",
      "statusOffsetGeneral": "#96c7f2",
      "statusOffsetError": "#f3aeaf"
    },
    "background": {
      "generalMain": "#ffffff",
      "generalMainInverted": "#1c1c1c",
      "generalMainAltDarkMode": "#ffffff",
      "generalMainAlt": "#f7f7f8",
      "generalUnderlying": "#f5f5f8",
      "generalNoticeable": "#ededef",
      "generalNegative": "#3e3e3e",
      "generalNegativeSolid": "#1c1c1c",
      "generalNegativeSubdued": "#505050",
      "generalInteractive": "#505050",
      "generalInteractiveInverted": "#eef1fd",
      "generalInteractiveSubdued": "#8F8F8F",
      "generalOverlay": "rgba(0, 0, 0, 0.4392)",
      "generalOverlaySubtle": "rgba(0, 0, 0, 0.0902)",
      "generalOverlayOnAccentHovered": "rgba(255, 255, 255, 0.2510)",
      "generalOverlayOnAccentPressed": "rgba(0, 0, 0, 0.2196)",
      "generalOverlayOnColorlessHovered": "rgba(0, 0, 0, 0.0471)",
      "generalOverlayOnColorlessPressed": "rgba(0, 0, 0, 0.0902)",
      "generalOverlayOnColorlessInvertedHovered": "rgba(255, 255, 255, 0.1804)",
      "generalOverlayOnColorlessInvertedPressed": "rgba(255, 255, 255, 0.0902)",
      "brandBrand1Primary": "#5146CE",
      "brandBrand1SecondaryHovered": "rgba(81, 70, 206, 0.0902)",
      "brandBrand1SecondaryPressed": "rgba(81, 70, 206, 0.1412)",
      "brandBrand2Primary": "#1A9991",
      "brandBrand2SecondaryHovered": "rgba(26, 153, 145, 0.0902)",
      "brandBrand2SecondaryPressed": "rgba(26, 153, 145, 0.1412)",
      "statusInfo": "#f5faff",
      "statusInfoHovered": "rgba(0, 145, 255, 0.0902)",
      "statusInfoPressed": "rgba(0, 145, 255, 0.1412)",
      "statusInfoInvertedHovered": "rgba(54, 158, 255, 0.2510)",
      "statusInfoInvertedPressed": "rgba(54, 158, 255, 0.1216)",
      "statusSuccess": "#f2fcf5",
      "statusWarning": "#fff9ed",
      "statusWarningHovered": "rgba(255, 178, 36, 0.0902)",
      "statusWarningPressed": "rgba(255, 178, 36, 0.1412)",
      "statusError": "#fff8f8",
      "statusErrorHovered": "rgba(229, 72, 77, 0.0902)",
      "statusErrorPressed": "rgba(229, 72, 77, 0.1412)",
      "statusDisabled": "#d9d9db",
      "statusDisabledSubtle": "#f5f5f8"
    }
  },
  "darkTheme": {
    "foreground": {
      "generalPrimary": "#ededed",
      "generalPrimaryInverted": "#262e34",
      "generalSecondary": "#a6a6a6",
      "generalTertiary": "#7e7e7e",
      "generalLink": "#7ebfff",
      "generalLinkVisited": "#1d6dc3",
      "generalLinkPressed": "#eaf6ff",
      "generalInteractive": "#d9e2fc",
      "generalInteractiveInverted": "#505050",
      "generalInteractiveInvertedAlt": "#505050",
      "generalWhiteStable": "#ffffff",
      "generalBlackWhite": "#ffffff",
      "generalTransparent": "rgba(255, 255, 255, 0.3882)",
      "brandBrand1": "#3c76e8",
      "brandBrand2": "#ec5e41",
      "statusInfo": "#7ebfff",
      "statusInfoInverted": "#006adc",
      "statusInfoSubdued": "#0091ff",
      "statusSuccess": "#4cc38a",
      "statusSuccessSubdued": "#30a46c",
      "statusWarning": "#f1a10d",
      "statusWarningSubdued": "#ffb224",
      "statusError": "#ff6369",
      "statusErrorSubdued": "#e5484d",
      "statusDisabled": "#707070"
    },
    "border": {
      "generalMain": "#707070",
      "generalMainSubtle": "#343434",
      "generalMainSolid": "#ededed",
      "generalInteractive": "#d9e2fc",
      "generalInteractiveInverted": "#505050",
      "generalInteractiveHovered": "#a6a6a6",
      "generalInteractivePressed": "#707070",
      "generalWhite": "#ffffff",
      "brandBrand1": "#3c76e8",
      "brandBrand2": "#ec5e41",
      "statusInfo": "#7ebfff",
      "statusInfoInverted": "#006adc",
      "statusInfoSubdued": "#0091ff",
      "statusSuccessSubdued": "#30a46c",
      "statusWarning": "#f1a10d",
      "statusWarningSubdued": "#ffb224",
      "statusError": "#ff6369",
      "statusErrorSubdued": "#e5484d",
      "statusDisabled": "#505050",
      "statusOffsetGeneral": "#1d6dc3",
      "statusOffsetError": "#822025"
    },
    "background": {
      "generalMain": "#1c1c1c",
      "generalMainInverted": "#ffffff",
      "generalMainAltDarkMode": "#2e2e2e",
      "generalMainAlt": "#232323",
      "generalUnderlying": "#161616",
      "generalNoticeable": "#282828",
      "generalNegative": "#232323",
      "generalNegativeSolid": "#000000",
      "generalNegativeSubdued": "#343434",
      "generalInteractive": "#eef1fd",
      "generalInteractiveInverted": "#505050",
      "generalInteractiveSubdued": "#707070",
      "generalOverlay": "rgba(255, 255, 255, 0.3882)",
      "generalOverlaySubtle": "rgba(255, 255, 255, 0.0314)",
      "generalOverlayOnAccentHovered": "rgba(255, 255, 255, 0.2510)",
      "generalOverlayOnAccentPressed": "rgba(0, 0, 0, 0.2196)",
      "generalOverlayOnColorlessHovered": "rgba(255, 255, 255, 0.1804)",
      "generalOverlayOnColorlessPressed": "rgba(255, 255, 255, 0.0902)",
      "generalOverlayOnColorlessInvertedHovered": "rgba(0, 0, 0, 0.0471)",
      "generalOverlayOnColorlessInvertedPressed": "rgba(0, 0, 0, 0.0902)",
      "brandBrand1Primary": "#5146CE",
      "brandBrand1SecondaryHovered": "rgba(81, 70, 206, 0.2510)",
      "brandBrand1SecondaryPressed": "rgba(81, 70, 206, 0.1216)",
      "brandBrand2Primary": "#1A9991",
      "brandBrand2SecondaryHovered": "rgba(26, 153, 145, 0.2510)",
      "brandBrand2SecondaryPressed": "rgba(26, 153, 145, 0.1216)",
      "statusInfo": "#0f1b2d",
      "statusInfoHovered": "rgba(54, 158, 255, 0.2510)",
      "statusInfoPressed": "rgba(54, 158, 255, 0.1216)",
      "statusInfoInvertedHovered": "rgba(0, 145, 255, 0.0902)",
      "statusInfoInvertedPressed": "rgba(0, 145, 255, 0.1412)",
      "statusSuccess": "#0c1f17",
      "statusWarning": "#271700",
      "statusWarningHovered": "rgba(255, 203, 71, 0.2510)",
      "statusWarningPressed": "rgba(255, 203, 71, 0.1216)",
      "statusError": "#291415",
      "statusErrorHovered": "rgba(242, 85, 90, 0.2510)",
      "statusErrorPressed": "rgba(242, 85, 90, 0.1216)",
      "statusDisabled": "#3e3e3e",
      "statusDisabledSubtle": "#232323"
    }
  }
};
        